version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

formats: all

python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
